apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zpxp998vz-dotnet-basic
  janus-idp.io/tekton: zpxp998vz-dotnet-basic
  backstage.io/kubernetes-id: zpxp998vz-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zpxp998vz-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
